---
? - "/measure"
  - getmeas
: :paged: true
  :multi: false
  :time_format: :timestamp
  :extract_data_from: :measuregrps
? - measure
  - getintradayactivity
: :paged: false
  :multi: true
  :multi_field: :data_fields
  :multi_field_join: ","
  :time_format: :timestamp
  :extract_data_from: :series
? - sleep
  - get
: :paged: false
  :multi: true
  :multi_field: :data_fields
  :multi_field_join: ","
  :time_format: :timestamp
  :extract_data_from: :sleep
? - measure
  - getworkouts
: :paged: true
  :multi: false
  :time_format: :ymd
  :extract_data_from: :workout
