require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - '**/*.haml'
    - '**/*.js.erb'

# Metrics

Metrics/MethodLength:
  Max: 15

# Layout

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

# Rails

Rails/FilePath:
  EnforcedStyle: arguments

# Style

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'

Style/Documentation:
  Exclude:
    - 'app/controllers'

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Style/SymbolArray:
  EnforcedStyle: brackets
