---
http_interactions:
- request:
    method: get
    uri: https://api.twitter.com/1.1/statuses/user_timeline.json?include_rts=true&screen_name=tyler_throwaway
    body:
      encoding: UTF-8
      string: ''
    headers:
      User-Agent:
      - TwitterRubyGem/6.2.0
      Authorization:
      - OAuth oauth_consumer_key="TWITTER_OAUTH_KEY", oauth_nonce="e440c55502c92cbbbc70dad2a0252b92",
        oauth_signature="nst8l7wGlxByHnbPIjrZoaW1mig%3D", oauth_signature_method="HMAC-SHA1",
        oauth_timestamp="1563737272", oauth_token="some_nonsense", oauth_version="1.0"
      Connection:
      - close
      Host:
      - api.twitter.com
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Connection:
      - close
      Content-Length:
      - '62'
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Sun, 21 Jul 2019 19:27:52 GMT
      Server:
      - tsa_a
      Set-Cookie:
      - guest_id=v1%3A156373727270407591; Max-Age=63072000; Expires=Tue, 20 Jul 2021
        19:27:52 GMT; Path=/; Domain=.twitter.com
      - personalization_id="v1_8nh5muCamHC1kGtcIhx4TA=="; Max-Age=63072000; Expires=Tue,
        20 Jul 2021 19:27:52 GMT; Path=/; Domain=.twitter.com
      Strict-Transport-Security:
      - max-age=631138519
      X-Connection-Hash:
      - 4e6cf606e42a2a8669809af91fb83503
      X-Response-Time:
      - '6'
    body:
      encoding: UTF-8
      string: '{"errors":[{"code":89,"message":"Invalid or expired token."}]}'
    http_version: 
  recorded_at: Sun, 21 Jul 2019 19:27:52 GMT
recorded_with: VCR 5.0.0
