---
http_interactions:
- request:
    method: post
    uri: https://api.flickr.com/services/rest/
    body:
      encoding: US-ASCII
      string: user_id=67275002%40N00&min_upload_date=1556694000&max_upload_date=1583049600&page=1&method=flickr.people.getPhotos&format=json&nojsoncallback=1
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Flickr/2.0.2 (+https://github.com/cyclotron3k/flickr)
      Authorization:
      - OAuth realm="https://api.flickr.com/services/rest/", oauth_consumer_key="FLICKR_OAUTH_KEY",
        oauth_nonce="6S2PsQM2pYMINBvka71za4yM7hyx%2F%2FCEgh7I%2FZHU0N8%3D", oauth_signature="FLICKR_OAUTH_SECRET%26",
        oauth_signature_method="PLAINTEXT", oauth_timestamp="1584916691", oauth_token="FLICKR_TEST_USER_TOKEN",
        oauth_version="1.0"
      Content-Type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Date:
      - Sun, 22 Mar 2020 22:38:11 GMT
      Server:
      - Apache/2.4.41 (Ubuntu)
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Cache:
      - Miss from cloudfront
      Via:
      - 1.1 12f10b9e24f9ba8391bdd5a5e055c81c.cloudfront.net (CloudFront)
      X-Amz-Cf-Pop:
      - SFO20-C1
      X-Amz-Cf-Id:
      - ejcgczQexpbdCoVq3PqgO8h6MGL1YHflzckiuOOLqBjjt8QI-Ce3XA==
    body:
      encoding: ASCII-8BIT
      string: '{"photos":{"page":1,"pages":1,"perpage":100,"total":"27","photo":[{"id":"49532795116","owner":"67275002@N00","secret":"9bcbfa45f6","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"49462469243","owner":"67275002@N00","secret":"2c2aa14d16","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"49462467063","owner":"67275002@N00","secret":"db402dbe9b","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"49269965758","owner":"67275002@N00","secret":"dc9f3c707e","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"49269916061","owner":"67275002@N00","secret":"e511a1a173","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"49140562231","owner":"67275002@N00","secret":"cbcefe6b16","server":"65535","farm":66,"title":"","ispublic":1,"isfriend":0,"isfamily":0},{"id":"49022293481","owner":"67275002@N00","secret":"f2c89d669d","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48966016048","owner":"67275002@N00","secret":"5797650382","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48961044066","owner":"67275002@N00","secret":"fe1ddf4e52","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48950068168","owner":"67275002@N00","secret":"0e43f630c6","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48950489691","owner":"67275002@N00","secret":"71daf58505","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48669256258","owner":"67275002@N00","secret":"f43d7b5b4a","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48669598801","owner":"67275002@N00","secret":"940baa6a69","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48669756317","owner":"67275002@N00","secret":"17927d9202","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48668736901","owner":"67275002@N00","secret":"5db2272425","server":"65535","farm":66,"title":"Seine","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48667549877","owner":"67275002@N00","secret":"87af805bb1","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48666054311","owner":"67275002@N00","secret":"53750b2e75","server":"65535","farm":66,"title":"Merritt","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48665588078","owner":"67275002@N00","secret":"d75734e747","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48627375453","owner":"67275002@N00","secret":"1a157311b5","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48625838506","owner":"67275002@N00","secret":"869facd4b1","server":"65535","farm":66,"title":"Balaton","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48625198372","owner":"67275002@N00","secret":"830757610b","server":"65535","farm":66,"title":"Seine","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48625051811","owner":"67275002@N00","secret":"dbb09f2f7c","server":"65535","farm":66,"title":"Seine","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48624787797","owner":"67275002@N00","secret":"2f50b1fdb3","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48613435378","owner":"67275002@N00","secret":"60e8f73705","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48610165543","owner":"67275002@N00","secret":"83fcedc4a7","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"48549159351","owner":"67275002@N00","secret":"30de18e0b3","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0},{"id":"47955972296","owner":"67275002@N00","secret":"305336527a","server":"65535","farm":66,"title":"*","ispublic":1,"isfriend":0,"isfamily":0}]},"stat":"ok"}'
    http_version: null
  recorded_at: Sun, 22 Mar 2020 22:38:11 GMT
- request:
    method: post
    uri: https://api.flickr.com/services/rest/
    body:
      encoding: US-ASCII
      string: user_id=67275002%40N00&min_upload_date=1556694000&max_upload_date=1583049600&page=2&method=flickr.people.getPhotos&format=json&nojsoncallback=1
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Flickr/2.0.2 (+https://github.com/cyclotron3k/flickr)
      Authorization:
      - OAuth realm="https://api.flickr.com/services/rest/", oauth_consumer_key="FLICKR_OAUTH_KEY",
        oauth_nonce="jUKZJe9nPO7T1rLzzExAGWUmMEkn8FDttHO4YNO2MMU%3D", oauth_signature="FLICKR_OAUTH_SECRET%26",
        oauth_signature_method="PLAINTEXT", oauth_timestamp="1584916691", oauth_token="FLICKR_TEST_USER_TOKEN",
        oauth_version="1.0"
      Content-Type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json
      Content-Length:
      - '78'
      Connection:
      - keep-alive
      Date:
      - Sun, 22 Mar 2020 22:38:12 GMT
      Server:
      - Apache/2.4.41 (Ubuntu)
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Cache:
      - Miss from cloudfront
      Via:
      - 1.1 c1caaceb6655a57ae014aef7bc8ec389.cloudfront.net (CloudFront)
      X-Amz-Cf-Pop:
      - SFO20-C1
      X-Amz-Cf-Id:
      - WOd0zvsLVnnPuMtSXGiqMRq51zVtfyBu9RP6-QWL4M5wAzmDmNETFg==
    body:
      encoding: UTF-8
      string: '{"stat":"fail","code":1,"message":"Required arguments missing"}'
    http_version: null
  recorded_at: Sun, 22 Mar 2020 22:38:12 GMT
- request:
    method: post
    uri: https://api.flickr.com/services/rest/
    body:
      encoding: US-ASCII
      string: method=flickr.reflection.getMethods&format=json&nojsoncallback=1
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Flickr/2.0.2 (+https://github.com/cyclotron3k/flickr)
      Authorization:
      - OAuth realm="https://api.flickr.com/services/rest/", oauth_consumer_key="FLICKR_OAUTH_KEY",
        oauth_nonce="5B8NGvgG0oN%2FwwUagXoV8wv7po1yvB4B1B2TZaaoNNI%3D", oauth_signature="FLICKR_OAUTH_SECRET%26",
        oauth_signature_method="PLAINTEXT", oauth_timestamp="1584917167", oauth_token="",
        oauth_version="1.0"
      Content-Type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Date:
      - Sun, 22 Mar 2020 22:46:07 GMT
      Server:
      - Apache/2.4.41 (Ubuntu)
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Cache:
      - Miss from cloudfront
      Via:
      - 1.1 80b537f2cda1e26d67673c227b9e06a7.cloudfront.net (CloudFront)
      X-Amz-Cf-Pop:
      - SFO20-C1
      X-Amz-Cf-Id:
      - xLY8nKYWFMNg12HSCPHaVHM6H4Um3VWNRtm_5dXKXzC0HG7OOYMNzA==
    body:
      encoding: UTF-8
      string: '{"methods":{"method":[{"_content":"flickr.activity.userComments"},{"_content":"flickr.activity.userPhotos"},{"_content":"flickr.auth.checkToken"},{"_content":"flickr.auth.getFrob"},{"_content":"flickr.auth.getFullToken"},{"_content":"flickr.auth.getToken"},{"_content":"flickr.auth.oauth.checkToken"},{"_content":"flickr.auth.oauth.getAccessToken"},{"_content":"flickr.blogs.getList"},{"_content":"flickr.blogs.getServices"},{"_content":"flickr.blogs.postPhoto"},{"_content":"flickr.cameras.getBrandModels"},{"_content":"flickr.cameras.getBrands"},{"_content":"flickr.collections.getInfo"},{"_content":"flickr.collections.getTree"},{"_content":"flickr.commons.getInstitutions"},{"_content":"flickr.contacts.getList"},{"_content":"flickr.contacts.getListRecentlyUploaded"},{"_content":"flickr.contacts.getPublicList"},{"_content":"flickr.contacts.getTaggingSuggestions"},{"_content":"flickr.favorites.add"},{"_content":"flickr.favorites.getContext"},{"_content":"flickr.favorites.getList"},{"_content":"flickr.favorites.getPublicList"},{"_content":"flickr.favorites.remove"},{"_content":"flickr.galleries.addPhoto"},{"_content":"flickr.galleries.create"},{"_content":"flickr.galleries.editMeta"},{"_content":"flickr.galleries.editPhoto"},{"_content":"flickr.galleries.editPhotos"},{"_content":"flickr.galleries.getInfo"},{"_content":"flickr.galleries.getList"},{"_content":"flickr.galleries.getListForPhoto"},{"_content":"flickr.galleries.getPhotos"},{"_content":"flickr.galleries.removePhoto"},{"_content":"flickr.groups.browse"},{"_content":"flickr.groups.discuss.replies.add"},{"_content":"flickr.groups.discuss.replies.delete"},{"_content":"flickr.groups.discuss.replies.edit"},{"_content":"flickr.groups.discuss.replies.getInfo"},{"_content":"flickr.groups.discuss.replies.getList"},{"_content":"flickr.groups.discuss.topics.add"},{"_content":"flickr.groups.discuss.topics.getInfo"},{"_content":"flickr.groups.discuss.topics.getList"},{"_content":"flickr.groups.getInfo"},{"_content":"flickr.groups.join"},{"_content":"flickr.groups.joinRequest"},{"_content":"flickr.groups.leave"},{"_content":"flickr.groups.members.getList"},{"_content":"flickr.groups.pools.add"},{"_content":"flickr.groups.pools.getContext"},{"_content":"flickr.groups.pools.getGroups"},{"_content":"flickr.groups.pools.getPhotos"},{"_content":"flickr.groups.pools.remove"},{"_content":"flickr.groups.search"},{"_content":"flickr.interestingness.getList"},{"_content":"flickr.machinetags.getNamespaces"},{"_content":"flickr.machinetags.getPairs"},{"_content":"flickr.machinetags.getPredicates"},{"_content":"flickr.machinetags.getRecentValues"},{"_content":"flickr.machinetags.getValues"},{"_content":"flickr.panda.getList"},{"_content":"flickr.panda.getPhotos"},{"_content":"flickr.people.findByEmail"},{"_content":"flickr.people.findByUsername"},{"_content":"flickr.people.getGroups"},{"_content":"flickr.people.getInfo"},{"_content":"flickr.people.getLimits"},{"_content":"flickr.people.getPhotos"},{"_content":"flickr.people.getPhotosOf"},{"_content":"flickr.people.getPublicGroups"},{"_content":"flickr.people.getPublicPhotos"},{"_content":"flickr.people.getUploadStatus"},{"_content":"flickr.photos.addTags"},{"_content":"flickr.photos.comments.addComment"},{"_content":"flickr.photos.comments.deleteComment"},{"_content":"flickr.photos.comments.editComment"},{"_content":"flickr.photos.comments.getList"},{"_content":"flickr.photos.comments.getRecentForContacts"},{"_content":"flickr.photos.delete"},{"_content":"flickr.photos.geo.batchCorrectLocation"},{"_content":"flickr.photos.geo.correctLocation"},{"_content":"flickr.photos.geo.getLocation"},{"_content":"flickr.photos.geo.getPerms"},{"_content":"flickr.photos.geo.photosForLocation"},{"_content":"flickr.photos.geo.removeLocation"},{"_content":"flickr.photos.geo.setContext"},{"_content":"flickr.photos.geo.setLocation"},{"_content":"flickr.photos.geo.setPerms"},{"_content":"flickr.photos.getAllContexts"},{"_content":"flickr.photos.getContactsPhotos"},{"_content":"flickr.photos.getContactsPublicPhotos"},{"_content":"flickr.photos.getContext"},{"_content":"flickr.photos.getCounts"},{"_content":"flickr.photos.getExif"},{"_content":"flickr.photos.getFavorites"},{"_content":"flickr.photos.getInfo"},{"_content":"flickr.photos.getNotInSet"},{"_content":"flickr.photos.getPerms"},{"_content":"flickr.photos.getPopular"},{"_content":"flickr.photos.getRecent"},{"_content":"flickr.photos.getSizes"},{"_content":"flickr.photos.getUntagged"},{"_content":"flickr.photos.getWithGeoData"},{"_content":"flickr.photos.getWithoutGeoData"},{"_content":"flickr.photos.licenses.getInfo"},{"_content":"flickr.photos.licenses.setLicense"},{"_content":"flickr.photos.notes.add"},{"_content":"flickr.photos.notes.delete"},{"_content":"flickr.photos.notes.edit"},{"_content":"flickr.photos.people.add"},{"_content":"flickr.photos.people.delete"},{"_content":"flickr.photos.people.deleteCoords"},{"_content":"flickr.photos.people.editCoords"},{"_content":"flickr.photos.people.getList"},{"_content":"flickr.photos.recentlyUpdated"},{"_content":"flickr.photos.removeTag"},{"_content":"flickr.photos.search"},{"_content":"flickr.photos.setContentType"},{"_content":"flickr.photos.setDates"},{"_content":"flickr.photos.setMeta"},{"_content":"flickr.photos.setPerms"},{"_content":"flickr.photos.setSafetyLevel"},{"_content":"flickr.photos.setTags"},{"_content":"flickr.photos.suggestions.approveSuggestion"},{"_content":"flickr.photos.suggestions.getList"},{"_content":"flickr.photos.suggestions.rejectSuggestion"},{"_content":"flickr.photos.suggestions.removeSuggestion"},{"_content":"flickr.photos.suggestions.suggestLocation"},{"_content":"flickr.photos.transform.rotate"},{"_content":"flickr.photos.upload.checkTickets"},{"_content":"flickr.photosets.addPhoto"},{"_content":"flickr.photosets.comments.addComment"},{"_content":"flickr.photosets.comments.deleteComment"},{"_content":"flickr.photosets.comments.editComment"},{"_content":"flickr.photosets.comments.getList"},{"_content":"flickr.photosets.create"},{"_content":"flickr.photosets.delete"},{"_content":"flickr.photosets.editMeta"},{"_content":"flickr.photosets.editPhotos"},{"_content":"flickr.photosets.getContext"},{"_content":"flickr.photosets.getInfo"},{"_content":"flickr.photosets.getList"},{"_content":"flickr.photosets.getPhotos"},{"_content":"flickr.photosets.orderSets"},{"_content":"flickr.photosets.removePhoto"},{"_content":"flickr.photosets.removePhotos"},{"_content":"flickr.photosets.reorderPhotos"},{"_content":"flickr.photosets.setPrimaryPhoto"},{"_content":"flickr.places.find"},{"_content":"flickr.places.findByLatLon"},{"_content":"flickr.places.getChildrenWithPhotosPublic"},{"_content":"flickr.places.getInfo"},{"_content":"flickr.places.getInfoByUrl"},{"_content":"flickr.places.getPlaceTypes"},{"_content":"flickr.places.getShapeHistory"},{"_content":"flickr.places.getTopPlacesList"},{"_content":"flickr.places.placesForBoundingBox"},{"_content":"flickr.places.placesForContacts"},{"_content":"flickr.places.placesForTags"},{"_content":"flickr.places.placesForUser"},{"_content":"flickr.places.resolvePlaceId"},{"_content":"flickr.places.resolvePlaceURL"},{"_content":"flickr.places.tagsForPlace"},{"_content":"flickr.prefs.getContentType"},{"_content":"flickr.prefs.getGeoPerms"},{"_content":"flickr.prefs.getHidden"},{"_content":"flickr.prefs.getPrivacy"},{"_content":"flickr.prefs.getSafetyLevel"},{"_content":"flickr.profile.getProfile"},{"_content":"flickr.push.getSubscriptions"},{"_content":"flickr.push.getTopics"},{"_content":"flickr.push.subscribe"},{"_content":"flickr.push.unsubscribe"},{"_content":"flickr.reflection.getMethodInfo"},{"_content":"flickr.reflection.getMethods"},{"_content":"flickr.stats.getCollectionDomains"},{"_content":"flickr.stats.getCollectionReferrers"},{"_content":"flickr.stats.getCollectionStats"},{"_content":"flickr.stats.getCSVFiles"},{"_content":"flickr.stats.getPhotoDomains"},{"_content":"flickr.stats.getPhotoReferrers"},{"_content":"flickr.stats.getPhotosetDomains"},{"_content":"flickr.stats.getPhotosetReferrers"},{"_content":"flickr.stats.getPhotosetStats"},{"_content":"flickr.stats.getPhotoStats"},{"_content":"flickr.stats.getPhotostreamDomains"},{"_content":"flickr.stats.getPhotostreamReferrers"},{"_content":"flickr.stats.getPhotostreamStats"},{"_content":"flickr.stats.getPopularPhotos"},{"_content":"flickr.stats.getTotalViews"},{"_content":"flickr.tags.getClusterPhotos"},{"_content":"flickr.tags.getClusters"},{"_content":"flickr.tags.getHotList"},{"_content":"flickr.tags.getListPhoto"},{"_content":"flickr.tags.getListUser"},{"_content":"flickr.tags.getListUserPopular"},{"_content":"flickr.tags.getListUserRaw"},{"_content":"flickr.tags.getMostFrequentlyUsed"},{"_content":"flickr.tags.getRelated"},{"_content":"flickr.test.echo"},{"_content":"flickr.test.login"},{"_content":"flickr.test.null"},{"_content":"flickr.testimonials.addTestimonial"},{"_content":"flickr.testimonials.approveTestimonial"},{"_content":"flickr.testimonials.deleteTestimonial"},{"_content":"flickr.testimonials.editTestimonial"},{"_content":"flickr.testimonials.getAllTestimonialsAbout"},{"_content":"flickr.testimonials.getAllTestimonialsAboutBy"},{"_content":"flickr.testimonials.getAllTestimonialsBy"},{"_content":"flickr.testimonials.getPendingTestimonialsAbout"},{"_content":"flickr.testimonials.getPendingTestimonialsAboutBy"},{"_content":"flickr.testimonials.getPendingTestimonialsBy"},{"_content":"flickr.testimonials.getTestimonialsAbout"},{"_content":"flickr.testimonials.getTestimonialsAboutBy"},{"_content":"flickr.testimonials.getTestimonialsBy"},{"_content":"flickr.urls.getGroup"},{"_content":"flickr.urls.getUserPhotos"},{"_content":"flickr.urls.getUserProfile"},{"_content":"flickr.urls.lookupGallery"},{"_content":"flickr.urls.lookupGroup"},{"_content":"flickr.urls.lookupUser"}]},"stat":"ok"}'
    http_version: null
  recorded_at: Sun, 22 Mar 2020 22:46:07 GMT
recorded_with: VCR 5.1.0
