---
http_interactions:
- request:
    method: get
    uri: https://www.rescuetime.com/anapi/data?format=csv&key=some_nonsense&operation=select&perspective=interval&resolution_time=minute&restrict_begin=2019-07-05&restrict_end=2019-07-08&restrict_kind=activity&version=0
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - www.rescuetime.com
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Thu, 11 Jul 2019 03:01:45 GMT
      Expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      Pragma:
      - no-cache
      Server:
      - nginx
      Strict-Transport-Security:
      - max-age=31536000
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Request-Id:
      - fe801cc9-53c9-4912-899f-5b2178e4a83d
      X-Runtime:
      - '0.016775'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '54'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"error":"# key not found","messages":"key not found"}'
    http_version: 
  recorded_at: Thu, 11 Jul 2019 03:01:45 GMT
recorded_with: VCR 5.0.0
